on:
  issue_comment:
    types: [created]

name: comment
jobs:
  run:
    name: PR comment
    if: ${{ (github.event.issue.pull_request) && (github.event.comment.body == 'trigger words')}}
    runs-on: ubuntu-latest
    env:
      COMMENT: ${{ github.event.comment.body }}
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$COMMENT"
        echo "$GITHUB_CONTEXT"
    - name: Fail
      run: exit 1
    - name: Message success
      if: ${{ success() }}
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Deployment succeeded! ✅',
          });
    - name: Message failure
      if: ${{ failure() }}
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Deployment failed! ❌',
          });
